export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const MOVE_ACTIVITY = 'MOVE_ACTIVITY';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const SET_ACTIVITY = 'SET_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const OPEN_MODAL = 'OPEN_MODAL';
