export const ModalStyle = {
    position: 'absolute',
    top: '50%',
    left: '50%',
    right: 'auto',
    bottom: 'auto',
    border: '0px',
    overflow: 'auto',
    borderRadius: '4px',
    outline: 'none',
    padding: '20px 30px',
    marginRight: '-50%',
    transform: 'translate(-50%, -50%)',
    maxWidth: '500px',
    background: '#fff',
    minWidth: '350px',
};
